# Configuration

github:
  org: sparkbountybot
  watch_interval_seconds: 300

gmail:
  email: your@gmail.com
  password: your-app-password
  check_interval_seconds: 300

trading:
  alpaca_api_key: PKYKHN5LV53HDV2GXRSDA6WJM6
  alpaca_secret_key: tzU24QxdnsugiCB5DUWb5bMZdVifBY5rfEhr2by4DiK
  base_url: https://paper-api.alpaca.markets
  paper: true
  max_position_pct: 0.3
  max_total_risk: 0.05

email:
  from: bountybot@sparkbountybot.com

sendgrid:
  api_key: your-sendgrid-key
